
import React, { useState, useEffect, useRef } from 'react';
import QRCode from 'qrcode';
import { jsPDF } from 'jspdf';
import { QRSettings, ExportFormat } from './types';
import Header from './components/Header';
import ControlPanel from './components/ControlPanel';
import PreviewCard from './components/PreviewCard';
import Footer from './components/Footer';

const App: React.FC = () => {
  const [settings, setSettings] = useState<QRSettings>({
    content: 'https://google.com',
    fgColor: '#000000',
    bgColor: '#ffffff',
    size: 400,
    margin: 2,
    errorCorrectionLevel: 'M',
  });

  const [qrDataUrl, setQrDataUrl] = useState<string>('');
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    generateQRCode();
  }, [settings]);

  const generateQRCode = async () => {
    try {
      if (!settings.content.trim()) {
        setQrDataUrl('');
        return;
      }

      const url = await QRCode.toDataURL(settings.content, {
        width: settings.size,
        margin: settings.margin,
        color: {
          dark: settings.fgColor,
          light: settings.bgColor,
        },
        errorCorrectionLevel: settings.errorCorrectionLevel,
      });
      setQrDataUrl(url);
    } catch (err) {
      console.error('Failed to generate QR Code:', err);
    }
  };

  const downloadFile = (format: ExportFormat) => {
    if (!qrDataUrl) return;

    const fileName = `qr-spark-${Date.now()}`;

    if (format === ExportFormat.PDF) {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });
      
      // Calculate centering for A4 (210mm x 297mm)
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const qrSize = 120; // 120mm
      const x = (pdfWidth - qrSize) / 2;
      const y = (pdfHeight - qrSize) / 2;

      pdf.addImage(qrDataUrl, 'PNG', x, y, qrSize, qrSize);
      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text('Generated by QR Spark Pro', pdfWidth / 2, y + qrSize + 10, { align: 'center' });
      pdf.save(`${fileName}.pdf`);
    } else {
      const link = document.createElement('a');
      link.download = `${fileName}.${format}`;
      
      // If JPG, we need to handle the conversion if the source is PNG dataUrl
      if (format === ExportFormat.JPG) {
        const canvas = document.createElement('canvas');
        const img = new Image();
        img.onload = () => {
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.fillStyle = settings.bgColor;
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.drawImage(img, 0, 0);
            link.href = canvas.toDataURL('image/jpeg', 0.9);
            link.click();
          }
        };
        img.src = qrDataUrl;
      } else {
        link.href = qrDataUrl;
        link.click();
      }
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
      <Header />
      
      <main className="flex-grow container mx-auto px-4 py-8 md:py-12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <ControlPanel settings={settings} setSettings={setSettings} />
          
          <div className="flex flex-col gap-6 sticky top-24">
            <PreviewCard 
              qrDataUrl={qrDataUrl} 
              onDownload={downloadFile}
              hasContent={!!settings.content.trim()}
            />
            
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <i className="fa-solid fa-circle-info text-blue-500"></i>
                Usage Tips
              </h3>
              <ul className="space-y-3 text-sm text-slate-600">
                <li className="flex gap-3">
                  <span className="bg-blue-100 text-blue-600 w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold">1</span>
                  Enter any text, URL, or number in the input field.
                </li>
                <li className="flex gap-3">
                  <span className="bg-blue-100 text-blue-600 w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold">2</span>
                  Customize the colors and size to match your branding.
                </li>
                <li className="flex gap-3">
                  <span className="bg-blue-100 text-blue-600 w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold">3</span>
                  Higher error correction is better for complex backgrounds or small prints.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default App;
